[simulator]
configs = ["p", "r", "ss", "pss", "fs", "rs"]
datasets = [ "training", "testing", "validation" ]
nterms = 16
image-directory = "images"

[training]
size = 10000
filename = "training-lens.csv"
roulette = "training.csv"

[testing]
size = 10000
filename = "testing-lens.csv"
roulette = "testing.csv"

[validation]
size = 10000
filename = "validation-lens.csv"
roulette = "validation.csv"

[lens]
chi = 50
einstein-min = 10
einstein-max = 50

[source]
mode = "e"
sigma-min = 1
sigma-max = 60
sigma2-min = 1
sigma2-max = 40
theta-min = 0
theta-max = 179
position = "polar"

[position]
phi-min = 0
phi-max = 359
r-min = "einsteinR"
r-max = 100

